name: Unittests

on:
  push:
    branches: [ master, stable ]
  pull_request:
    branches: [ master, stable, twinifyv2 ]

jobs:
  unittests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install environment
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-cov
    - name: Install dependencies
      run: |
        python -m pip install .[compatible-dependencies]
    - name: Test with pytest
      run: |
        pytest --cov=twinify --cov-report term-missing tests/
